# Generated by Django 4.1.5 on 2023-09-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Person',
        ),
    ]
